---
kind: pipeline
type: docker
name: reviews

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node:9.2.0
  commands:
  - npm i
  - npm run build

trigger:
  branch:
  - master
  event:
  - pull_request

---
kind: pipeline
type: docker
name: build push deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node:9.2.0
  commands:
  - npm i
  - npm run build

- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: dockerhub_password
    repo: polygonio/ui-swagger
    tag:
    - ${DRONE_BRANCH/master/latest}
    - ${DRONE_COMMIT}
    username:
      from_secret: dockerhub_username

- name: service-staging
  pull: always
  image: polygonio/drone-kube
  settings:
    ca:
      from_secret: KUBE_CA_STAGING
    namespace: polygon-public
    server:
      from_secret: KUBE_SERVER_STAGING
    template: _deploy_/service.yml
    token:
      from_secret: KUBE_TOKEN_STAGING

- name: ingress-staging
  pull: always
  image: polygonio/drone-kube
  settings:
    ca:
      from_secret: KUBE_CA_STAGING
    namespace: polygon-public
    server:
      from_secret: KUBE_SERVER_STAGING
    template: _deploy_/ingress.yml
    token:
      from_secret: KUBE_TOKEN_STAGING
    zone: staging.
    additional_annotations: 
      nginx.ingress.kubernetes.io/server-snippet: 'add_header X-Robots-Tag "noindex, nofollow";'

- name: deploy-staging
  pull: always
  image: polygonio/drone-kube
  settings:
    ca:
      from_secret: KUBE_CA_STAGING
    commit: ${DRONE_COMMIT}
    namespace: polygon-public
    number: ${DRONE_BUILD_NUMBER}
    replica_count: 1
    server:
      from_secret: KUBE_SERVER_STAGING
    template: _deploy_/deployment.yml
    token:
      from_secret: KUBE_TOKEN_STAGING
    zone: staging.

- name: slack
  image: plugins/slack
  settings:
    channel: drone-ui-deploy
    template: "{{#if build.pull }}\n  *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>\n{{else}}\n  *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)\n{{/if}} Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Author: {{ build.author }} <{{ build.link }}|Visit build page ↗>\n"
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push


---
kind: pipeline
type: docker
name: build and deploy to prod

platform:
  os: linux
  arch: amd64

steps:

  - name: service-prod
    pull: always
    image: polygonio/drone-kube
    settings:
      ca:
        from_secret: KUBE_CA
      namespace: polygon-public
      server:
        from_secret: KUBE_SERVER
      template: _deploy_/service.yml
      token:
        from_secret: KUBE_TOKEN

  - name: ingress-prod
    pull: always
    image: polygonio/drone-kube
    settings:
      ca:
        from_secret: KUBE_CA
      namespace: polygon-public
      server:
        from_secret: KUBE_SERVER
      template: _deploy_/ingress.yml
      token:
        from_secret: KUBE_TOKEN

  - name: deploy-prod
    pull: always
    image: polygonio/drone-kube
    settings:
      ca:
        from_secret: KUBE_CA
      commit: ${DRONE_COMMIT}
      namespace: polygon-public
      number: ${DRONE_BUILD_NUMBER}
      replica_count: 3
      server:
        from_secret: KUBE_SERVER
      template: _deploy_/deployment.yml
      token:
        from_secret: KUBE_TOKEN

  - name: slack
    image: plugins/slack
    settings:
      channel: drone-ui-deploy
      template: "{{#if build.pull }}\n  *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>\n{{else}}\n  *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)\n{{/if}} Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> Author: {{ build.author }} <{{ build.link }}|Visit build page ↗>\n"
      webhook:
        from_secret: slack_webhook
    when:
      status:
      - failure
      - success

trigger:
  event:
  - tag
  ref:
  - refs/tags/production-*
