
# App UI
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-swagger
  namespace: polygon-public
spec:
  replicas: {{replica_count}}
  template:
    metadata:
      labels:
        app: ui-swagger
        project: ui-swagger
    spec:
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
      containers:
        - name: ui-swagger
          image: polygonio/ui-swagger:{{commit}}
          env:
            - name: PORT
              value: '80'
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 6
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 1
              memory: 1G
            requests:
              cpu: .25
              memory: .5G
