
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-swagger
  namespace: polygon-public
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "{{zone}}polygon.io"
      - "www.{{zone}}polygon.io"
      secretName: polygon-ui-tls
  rules:
  - host: "{{zone}}polygon.io"
    http:
      paths:
      - path: /docs
        backend:
          serviceName: ui-swagger
          servicePort: 80
  - host: "www.{{zone}}polygon.io"
    http:
      paths:
      - path: /docs
        backend:
          serviceName: ui-swagger
          servicePort: 80





